name: 'Melody Compatibility Layer for Movable Type'
description: 'An addon for MT 4.x that aims to provide seamless compatiblity with all Melody plugins'
id: MelodyCompat
key: MelodyCompat
author_link: http://endevver.com/
author_name: Endevver
version: 1.0.0

init_app: $MelodyCompat::Melody::Compat::init_app

callbacks:
    post_init: $MelodyCompat::Melody::Compat::post_init

config_settings:
    JQueryURL:
        handler: $MelodyCompat::Melody::ConfigDirectives::_jquery_handler
tags:
    function:
        JQueryURL: $MelodyCompat::Melody::Tags::_hdlr_jquery_url

