name: 'Melody Compatibility Layer for Movable Type'
version: 1.0.3
description: 'An addon for MT 4.x that aims to provide seamless compatibility with all Melody plugins'
id: MelodyCompat
key: MelodyCompat
plugin_link: https://github.com/endevver/mt-plugin-melody-compat
author_name: "Jay Allen, Endevver LLC"
author_link: http://endevver.com/

init_app: $MelodyCompat::Melody::Compat::init_app

callbacks:
    post_init: $MelodyCompat::Melody::Compat::post_init
